### PR TITLE
jss crossing className in production

### LINKED ISSUE #141: jss crossing className in production
Hi, have a problem in prodaction mode with color picker when I open popup className crossing with main site style className.

Example:
on main theme:
```
<style data-jss="" data-meta="makeStyles">
.jss68 {
  width: 50px;
  height: 100px;
  z-index: 1;
  position: absolute;
}
.jss68 {
  z-index: inherit !important;
}
</style>
```

and on popup colorbox have same class:
```
<style data-jss="" data-meta="makeStyles">
.jss68 {
  width: 500px;
}
</style>
```

### PR DESCRIPTION
**Pull request by XmelesX**
fix #141

### CODE REVIEW

**Review by mikbry — APPROVED** [review]

**Comment by mikbry** [comment]
Thank @XmelesX !

**Comment by unusual-thoughts** [comment]
I'm affected by this issue on 1.1.0. @mikbry could you cut a new release with this fix ?

**Comment by SOTL** [comment]
Just stumbled across this too, +1 for new release! :)

**Comment by mikbry** [comment]
Sorry for the lack of update but I have a problem with npm publish 403 forbidden, I contacted the support, waiting for their response.

**Pull request merged**
